import { Verb } from './types';

export const VERBS: Verb[] = [
  'posted',
  'beaned',
  'licked',
  'shonked',
  'rekt',
  'vibrated',
  "awawawa'd",
  'snoofed',
  'networked',
  'boosted',
  'migrated',
  'patted',
  'woofed',
  'woemed',
  'swapped',
  'cached',
  'foxed',
  'typed',
  '[contributed](https://github.com/olivvybee/get-verbed)',
  'massaged',
  'kissed',
  'loved',
  'borked',
  'played',
  { word: 'railed', cw: 'lewd' },
  { word: 'broken', cw: 'lewd?' },
  'booped',
  'bonked',
  'petted',
  'generated',
  'goosed',
  'coded',
  'installed',
  'federated',
  'defederated',
  'fediblocked',
  'cuddled',
  'hugged',
  'squimshed',
  'squeezed',
  'snuggled',
  'noodled',
  'washed',
  { word: 'neobred', cw: 'lewd' },
  'trained',
  'clicked',
  'chomped',
  'floofed',
  'scritched',
  'discounted',
  'plushied',
  'formatted',
  'deleted',
  'edited',
  'copied',
  'pasted',
  'assembled',
  'bapped',
  "Blåhaj'd",
];

export const SUBJECTS: string[] = [
  'nerd',
  'dork',
  'cutie',
  'bro',
  'm8',
  'pal',
  'friendo',
  'pet',
  'pup',
  'bub',
  'buddy',
];
