export const VERBS = [
  'posted',
  'beaned',
  'licked',
  'shonked',
  'rekt',
  'vibrated',
  "awawawa'd",
  'snoofed',
  'networked',
  "maeow'd",
  'boosted',
  'migrated',
  'patted',
  'woofed',
  'woemed',
  'swapped',
  'cached',
  'foxed',
  'typed',
  '[contributed](https://github.com/olivvybee/get-verbed)',
  'massaged',
  'kissed',
  'loved',
  'borked',
  'played',
];

export const SUBJECTS = ['nerd', 'dork', 'cutie', 'bro', 'm8', 'pal'];
